name: CellMirror
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _pytorch_select=0.2
  - blas=1.0
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - intel-openmp=2022.1.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - openssl=1.1.1q
  - pip=22.2.2
  - pycparser=2.21
  - python=3.8.5
  - pytorch=1.4.0
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.39.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - anndata==0.8.0
    - attrs==23.1.0
    - backports-zoneinfo==0.2.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - contourpy==1.0.6
    - cycler==0.11.0
    - filelock==3.9.0
    - fonttools==4.38.0
    - h5py==3.7.0
    - huggingface-hub==0.11.1
    - idna==3.4
    - igraph==0.9.9
    - importlib-metadata==5.0.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - llvmlite==0.39.1
    - markupsafe==2.1.3
    - matplotlib==3.6.0
    - mizani==0.8.1
    - natsort==8.2.0
    - networkx==2.8.7
    - numba==0.56.3
    - numpy==1.22.4
    - packaging==21.3
    - palettable==3.3.0
    - pandas==1.5.1
    - patsy==0.5.3
    - pillow==9.3.0
    - plotnine==0.10.1
    - pot==0.9.3
    - pynndescent==0.5.8
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-igraph==0.9.9
    - pytz==2022.5
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.1
    - rpy2==3.5.1
    - sacremoses==0.0.53
    - scanpy==1.9.1
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - seaborn==0.12.1
    - session-info==1.0.0
    - statsmodels==0.13.2
    - stdlib-list==0.8.0
    - threadpoolctl==3.1.0
    - tokenizers==0.10.3
    - torchinfo==1.7.1
    - tqdm==4.64.1
    - transformers==4.4.2
    - typing-extensions==4.4.0
    - tzlocal==5.0.1
    - umap-learn==0.5.3
    - urllib3==1.26.13
    - wrapt==1.16.0
    - zipp==3.17.0